### ISSUE TITLE
static: implement basic rules

### ISSUE THREAD

**Issue by divy-work** [nestdotland/analyzer#1]
Feel free to take up one of these.

- [x] `ban-deno-run` - Report if `Deno.run` is called.
- [x] `ban-deno-plugin` - Report if `Deno.openPlugin` is called. - #5 
- [x] `check-deno-run` - This will be configurable, user will provide the particular command to be banned by the analyzer that is executed by `Deno.run` - #6 
- [ ] `ban-deno-env` - Report if `Deno.env` is called.
- [ ] `ban-deno-get-env` - Report if `Deno.env.get` is called.
- [ ] `ban-deno-set-env` - Report if `Deno.env.set` is called.
- [ ] `check-deno-get-env` - Configurable, ban a particular env that is card with `Deno.env.get`
- [ ] `check-deno-set-env` - Configurable, ban a particular env that is card with `Deno.env.set`
